[id="RawMemoryAccess"]
Raw Memory Access
=================
:author: Peter Donald
:date: 2007-03-07

The type +org.vmmagic.Address+ is used to represent a machine-dependent address type. +org.vmmagic.Address+ is an unboxed type. In the past, the base type +int+ was used to represent addresses but this approach had several shortcomings. First, the lack of abstraction makes porting nightmarish. Equally important is that Java type +int+ is signed whereas addresses are more appropriately considered unsigned. The difference is problematic since an unsigned comparison on +int+ is inexpressible in the Java programming language.

To overcome these problems, instances of +org.vmmagic.Address+ are used to represent addresses. The class supports the expected well-typed methods like adding an integer offset to an address to obtain another address, computing the difference of two addresses, and comparing addresses. Other operations that make sense on int but not on addresses are excluded like multiplication of addresses. Two methods deserve special attention: converting an address into an integer and the inverse. These methods should be avoided where possible.

Without special intervention, using a Java object to represent an address would be at best abysmally inefficient. Instead, when the Jikes RVM compiler encounters creation of an address object, it will return the primitive value that represents an address for that platform. Currently, the address type maps to either a 32-bit or 64-bit unsigned integer. Since an address is an unboxed type it must obey the rules outlined in Unboxed Types.
